name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Make in fresh
      run: apt update && apt dist-upgrade -y -q
    - name: Install build tools
      run:  apt install -y -q git ca-certificates cmake build-essential
    - name: Install build deps
      run:  apt install -y -q libpng-dev libx11-dev libgl1-mesa-dev
    - uses: actions/checkout@v2
    - name: Run CMakeLists.txt
      run: cmake .
    - name: Run Makefile
      run: make
    - name: Run Catch2 tests
      run: ./test/tests

      
